server:
  port: 8001
spring:
  application:
    name: cloud-payment-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver   # MySQL驱动包
    data-username: root
    password: ilovedz1997.
    url: jdbc://mysql:///springcloud2020?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源操作类型

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.cloud.entities # 所以entity别名类所在包
